# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "geometry", # <ofe_grid_data>
  "Col", # <ofe_grid_data>
  "Yield", # <ofe_grid_data>
  "Treatment", # <ofe_grid_data>
  "Rep", # <ofe_grid_data>
  "y", # <ofe_grid_data>
  "Row", # <ofe_grid_data>
  "temp_filter", # <ofe_grid_data>
  "x_original", # <plot_gridded_ofe>
  "y_original", # <plot_gridded_ofe>
  "Yield", # <plot_gridded_ofe>
  "Col", # <plot_gridded_ofe>
  "x_rough_rotation", # <plot_gridded_ofe>
  "y_rough_rotation", # <plot_gridded_ofe>
  "Odd Strip", # <plot_gridded_ofe>
  "x_rotated", # <plot_gridded_ofe>
  "y_rotated", # <plot_gridded_ofe>
  "geometry", # <plot_gridded_ofe>
  "treatment", # <lsd_graph>
  "means", # <lsd_graph>
  "group", # <lsd_graph>
  "lsd", # <lsd_graph>
  NULL
))
